FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80

#RUN mkdir /meuapp/public -p && touch /meuapp/public/index.js
CMD [ "nginx", "-g", "daemon off;" ]
